### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by serdtsekol1** [MrThearMan/graphene-django-extensions#60]
### I have read the docs thoroughly before making this feature request.

- [X] Yes

### I have read through other open issues, and my issue is not a duplicate.

- [X] Yes

### Description

How can I correctly transform the data structure on the frontend from the format `nameEn: ""` and `nameUk: ""` to the format 
`name: {en: "", uk: ""} `? I need to achieve this, but I can't find a way to override this logic.

### Motivation

I would like to have the option in the settings to specify `TYPE_LANGUAGE_FIELDS = "DICT"` or `TYPE_LANGUAGE_FIELDS = "NEW_FIELD"`.

This would be very helpful because without it, on the frontend, all language fields need to be listed in the request:
![image](https://github.com/MrThearMan/graphene-django-extensions/assets/15886730/e8e28fb6-d129-47e7-b757-c24cc0098c55)

I would like it to look something like this:
![image](https://github.com/MrThearMan/graphene-django-extensions/assets/15886730/59dc33a1-0f41-4754-a4f2-bf48f30411b4)

### Would you like to solve this issue yourself with a pull request?

No

**Comment by serdtsekol1** [comment]
After some thought, I decided that this is the best way to display multilingual fields:
![image](https://github.com/MrThearMan/graphene-django-extensions/assets/15886730/3dd5ee4c-45c0-4905-8366-c1812492b516)
If the site changes languages, you will not need to change the typing and queries to GQL

**Comment by MrThearMan** [comment]
Hi! Just to clarify, this seems to be related to the django-modeltranslation integration? There isn't really any easy way for you to constomize how these fields are created, since the code for this exists withing the DjangoNode class initialization [here](https://github.com/MrThearMan/graphene-django-extensions/blob/9877b41858c9dc42a195d9324ad46eb7dc69f3e2/graphene_django_extensions/bases.py#L155).

But, we've also had issues with how the library currently handles translatable fields. I'm considering the following things:

1. Exposing the "base field" (i.e. `name` instead of `nameEn`) seems unnecessary, since it has the same value as the default translation field.
    > There is also a bug in the optimizer if one only selects the base field, since django-modeltranslation will always fetch the default translation from the database a well, which now happens in a separate query (causes N+1).

2. When switching languages, and therefore which field should be used, it's [rather cumbersome](https://github.com/City-of-Helsinki/tilavarauspalvelu-ui/blob/c81f263250d99c68a762e590a41c1408c0914be0/packages/common/src/common/util.ts#L183-L203) to read data from the correct field. Frontend should be able to rely on GraphQL typing instead of dynamic types and doing string matching.

3. It should be possible to fetch all languages at the same time, since there might be use cases where you want to make the language switch client-side, or edit translations. Conversly, one should be allowed to only fetch one language.

4. All things being equal, we should prefer the solution that generates a smaller JSON payload.

The first proposal seems best in my opinion, considering all the points above. The second one requires string matching on the language key to select which language is used, and doesn't allow fetching just a single language (at least without filters). It also generates larger payloads.

But I think the first proposal is good, and I can probably implement it pretty easily. Each translatable field would be of a new ObjectType `Translatable`, which has its fields autogenerated based keys in `settings.LANGUAGES`. I'll make this behavior toggleable with a setting, but I'll likely make it the default in the future.

**Comment by john-psina** [comment]
It seems to me that in the case of:
```
name: {
en: "something EN",
uk: "something UK"
}
```
There is one problem. On the backend side, of course, there are no problems, but if you imagine that on the site it will be possible to enable / disable some languages, on the frontend side, it would probably be very inconvenient to make requests. Initially, on the frontend side, we can't know for sure what the languages ​​are on the backend, so the only way to make a correct request for a multilingual field is to send another request to first get the list of available languages, and then based on that to make a request for the multilingual field. Even in this case, it would be inconvenient to write types in GQL.

I might be wrong, but I'm of the opinion that it would probably be more convenient to get a list of `{language: string, value: any}` in multilingual fields, while also being able to apply a filter to get only the languages ​​that are needed

**Comment by john-psina** [comment]
Thank you! We look forward to your final decision on this matter.

**Comment by serdtsekol1** [comment]
> To simplify your point: the latter option has an advantage when the frontend doesn't know what languages are available.
> 
> Effectively, you can drive the translations on the frontend through the backend. It'll also be possible to add new (similar) languages on the backend and have them be available on the frontend without any changes (if you build your system for it).
> 
> I'll discuss your points at work with some of my colleagues. At the very least, I can make this configurable so you'll be able to implement it easier in a way you like.

I think it would be good if you added some of the options and made it possible to create custom options.

**Comment by MrThearMan** [comment]
Wrote an initial implementation in the [translation-refactor](https://github.com/MrThearMan/graphene-django-extensions/tree/translation-refactor) branch with both options. You can enable them by setting `EXPERIMENTAL_TRANSLATION_FIELDS=True` and `EXPERIMENTAL_TRANSLATION_FIELDS_KIND` to either `list` or `types` (default).

However, this is currently a braking change due to how `graphene-django` contructs filter arguments from filtersets (see. [`get_filtering_args_from_filterset`](https://github.com/graphql-python/graphene-django/blob/6f21dc7a9447721c6542f8ebc8fd60a510289566/graphene_django/filter/utils.py#L26-L103)).

Essentially, if you want to add the "base field" (i.e. `name`) to your filterset as a field like this:

```python
class ExampleFilterset(ModelFilterSet):
    class Meta:
        model = Example
        fields = ["name"]
```

Normally, this would create an `name__exact` filter for the name field, but since these new translation fields modify the name field to be an object type with fields, grahene-django is unable to figure out that name should still be a CharFilter. It looks at the registered object type for the filtered model to figure this out (see. [`get_field_type`](https://github.com/graphql-python/graphene-django/blob/6f21dc7a9447721c6542f8ebc8fd60a510289566/graphene_django/filter/utils.py#L11-L23)). GraphQL arguments must be input types, which a plain object type is not, so graphene fails to construct a valid schema (see [`create_fields_for_type`](https://github.com/graphql-python/graphene/blob/221afaf4c441a5e88e039440808d4810d5f040e7/graphene/types/schema.py#L323-L332), `arg_type = create_graphql_type(arg.type)` will create a plain object type, since `arg.type` was [deterimined to be a plain object type in `get_filtering_args_from_filterset`](https://github.com/graphql-python/graphene-django/blob/6f21dc7a9447721c6542f8ebc8fd60a510289566/graphene_django/filter/utils.py#L97-L101)).

I'm not seeing any great way to bypass this, aside from rewriting `get_filtering_args_from_filterset` to allow for some hook. Still, you can test the current implementation to see if it fits your needs or if you spot something else that's broken.

Note: `name_{lang}` filters do work normally, since it's just the base field that is overridden in the object types. I'm not sure if this is an acceptable behavior yet, since `name` filters work fine without `django-modeltranslation` installed, and the error this raised is not very clear on what's going wrong.

**Comment by serdtsekol1** [comment]
Here is an example of a well-functioning variant:
![image](https://github.com/MrThearMan/graphene-django-extensions/assets/15886730/293b750a-8143-4210-ad73-255745023497)
But as soon as I add an optional h1 (and I don't fill it with values), I somehow get the following error:
![image](https://github.com/MrThearMan/graphene-django-extensions/assets/15886730/829993ad-8761-4486-b807-df2319dde8cb)
#models.py
```python
class Category(MPTTModel):
    image = FileBrowseField(verbose_name=_('admin__image'), max_length=255, directory="category/", extensions=FILEBROWSER_EXTENSIONS['Image'] + ['.mp4'],
                            default="default/no_image.jpg", blank=True)
    image_banner_desktop = FileBrowseField(verbose_name=_('admin__banner_desktop'), help_text='Розмір 1500x470', max_length=255, directory="category/", extensions=FILEBROWSER_EXTENSIONS['Image'],
                                           blank=True, null=True)
    image_banner_mobile = FileBrowseField(verbose_name=_('admin__banner_mobile'), help_text='Розмір 530x600', max_length=255, directory="category/", extensions=FILEBROWSER_EXTENSIONS['Image'],
                                          blank=True, null=True)
    h1 = models.CharField(verbose_name=_("admin__h1"), max_length=255, null=True, blank=True, default="")
    id_import = models.CharField(verbose_name=_('ID для імпорту/експорту'), blank=True, null=True, max_length=255, default="")
    link = models.CharField("URL", null=True, blank=True, max_length=255)
    link_full = models.CharField("URL", null=True, blank=True, max_length=255)
    name = models.CharField(verbose_name=_('admin__name'), null=False, max_length=255)
    seo_title = models.CharField(verbose_name=_('admin__seo_title'), null=True, blank=True, max_length=255, default='')
    seo_description = models.TextField(verbose_name=_('admin__seo_description'), null=True, blank=True, default='')
    description = HTMLField(verbose_name=_('admin__description'), null=True, blank=True, default='')
    active = models.BooleanField(verbose_name=_('admin__active'), default=True, null=False)
    parent = TreeForeignKey('self', verbose_name=_('admin__parent'), null=True, blank=True, related_name='children', on_delete=models.CASCADE)
    added_date = models.DateTimeField(verbose_name=_('admin__added_date'), auto_now_add=True, auto_now=False)
    update_date = models.DateTimeField(verbose_name=_('admin__update_date'), auto_now_add=False, auto_now=True)
    image_alt = models.CharField(verbose_name=_("admin__image__alt"), max_length=255, null=True, blank=True, default="")
```

#translation.py
```python
@register(Category)
class CategoryTranslationOptions(TranslationOptions):
    fields = ('link', 'link_full', 'name', 'seo_title', 'seo_description', 'description', 'image_alt', 'h1', 'image_banner_desktop', 'image_banner_mobile')
    req_fields = ('name',)
    required_languages = set_required_languages(req_fields)
```
    

#GRAPQL 
```python
class CategoryFilter(ModelFilterSet):
    filter = UserDefinedFilter(
        model=Category,
        fields=['name', 'description'],
    )

    class Meta:
        order_by = ['id', 'name', 'description', 'parent', ]
        model = Category
class CategoryType(DjangoNode):
    product_set = DjangoConnectionField(lambda: ProductType)
    class Meta:
        model = Category
        interfaces = (graphene.relay.Node,)
        fields = (
            'id',
            'name',
            'description',
            'parent',
            'product_set',
        )
        filterset_class = CategoryFilter
class ProductQuery(graphene.ObjectType):
    category = graphene.Field(CategoryType, id=graphene.Int())
    def resolve_category(self, info, id):
        try:
            return Category.objects.get(pk=id)
        except Category.DoesNotExist:
            raise ObjectDoesNotExist(f'Category with id {id} does not exist')
```

And I also realized that it would be best if this behavior could be changed for each request separately (I don't know what would be more convenient, but it is definitely necessary), for example:
![image](https://github.com/MrThearMan/graphene-django-extensions/assets/15886730/6c047432-1f89-43cc-9ca7-e0e304e511b7)

Overall, everything works as expected, with one nuance: displaying all translations is almost never necessary on the client side, but only on the administrator side. Therefore, I think it would be appropriate to have the ability to change this for each request, as I mentioned above.

**Comment by MrThearMan** [comment]
The issue you have with null values is likely due to [how I made the translatable fields nullable](https://github.com/MrThearMan/graphene-django-extensions/blob/85eedf6c78ea21d70b727f1d23d166f3bf02d3e7/graphene_django_extensions/translation.py#L76). Specifically, the default language is always required instead of what the translation options indicate. This should be fixed.

We also had similar thoughs about customer/admin sides. On the customer side, it would be best if the following could be written:

```graphql
query {
  examples(lang: en) {
    edges {
      node {
        name
        subEntity {
          name
        }
      } 
    }
  }
}
```

...where `lang` is an Enum indicating that all translatable fields in the query should be in that language. `lang` could also be a header, or it could be be configurable to some other word to avoid collisions with existing filters.

On the admin side, we still need the option to list all language options. Perhaps this could be on a separate field, e.g. `nameTranslations: [LanguageString!]!`? This would remove issues with the current proposed implementation has with filtersets.

**Comment by serdtsekol1** [comment]
> On the admin side, we still need the option to list all language options. Perhaps this could be on a separate field, e.g. `nameTranslations: [LanguageString!]!`? This would remove issues with the current proposed implementation has with filtersets.

I'd like to clarify how this will look. Can you provide an example (of Query and Response) showing how this will look with the "list" and "types" options?

**Comment by MrThearMan** [comment]
Sure! Since we want all languages, the list format seems more appropriate:

```graphql
query {
  examples {
    edges {
      node {
        name
        nameTranslations {
          language
          value
        }
        subEntity {
          name
          nameTranslations {
            language
            value
          }
        }
      } 
    }
  }
}
```

Response

```json
{
  "data": {
    "examples": {
       "edges": [
          {
            "node": {
               "name": "<default language value>",
               "nameTranslations": [
                  {
                    "language": "en",
                    "value": "<english translation>"
                  },
                  {
                    "language": "fi",
                    "value": "<finnish translation>"
                  }
                ],
                "subEntity": {
                   "name": "<default language value>",
                   "nameTranslations": [
                     {
                       "language": "en",
                       "value": "<english translation>"
                     },
                     {
                       "language": "fi",
                       "value": "<finnish translation>"
                     }
                   ]
                 }
             }
          }
        ]
     }
  }
}
```

You could even add the previously mentioned `lang` filter to this, so that `"name": "<default language value>"` returns that language instead, while the list of translations remains the same. This way you don't need separate endpoints for customer and admin.

**Comment by serdtsekol1** [comment]
> Sure! Since we want all languages, the list format seems more appropriate:
> 
> ```graphql
> query {
>   examples {
>     edges {
>       node {
>         name
>         nameTranslations {
>           language
>           value
>         }
>         subEntity {
>           name
>           nameTranslations {
>             language
>             value
>           }
>         }
>       } 
>     }
>   }
> }
> ```
> 
> Response
> 
> ```json
> {
>   "data": {
>     "examples": {
>       "edges": [
>         {
>           "node": {
>             "name": "<default language value>",
>             "nameTranslations": [
>               {
>                 "language": "en",
>                 "value": "<english translation>"
>               },
>               {
>                 "language": "fi",
>                 "value": "<finnish translation>"
>               }
>             ],
>             "subEntity": {
>               "name": "<default language value>",
>               "nameTranslations": [
>                 {
>                   "language": "en",
>                   "value": "<english translation>"
>                 },
>                 {
>                   "language": "fi",
>                   "value": "<finnish translation>"
>                 }
>               ]
>             }
>           }
>         }
>       ]
>     }
>   }
> }
> ```
> 
> You could even add the previously mentioned `lang` filter to this, so that `"name": "<default language value>"` returns that language instead, while the list of translations remains the same. This way you don't need separate endpoints for customer and admin.

Oh great, this would probably be the best solution.

**Comment by MrThearMan** [comment]
I updated the implementation in the [translation-refactor](https://github.com/MrThearMan/graphene-django-extensions/tree/translation-refactor) branch. The `EXPERIMENTAL_TRANSLATION_FIELDS=True` flag now adds new `nameTranslations` fields (where `name` is the name of the translatable field) to the model's object type instead of modifying the translatable fields themselves. The `EXPERIMENTAL_TRANSLATION_FIELDS_KIND` flag also still works, but I changed the default to list.

With `EXPERIMENTAL_TRANSLATION_FIELDS=True`, the resolver of the base field (e.g. `name`) is changed such that it uses a translation based on the request user's desired language, which is determined by `django.utils.translation.get_language_from_request`. This uses either a `django_language` [cookie setting](https://docs.djangoproject.com/en/5.0/ref/settings/#language-cookie-name) (see. [`set_translation` view](https://docs.djangoproject.com/en/5.0/topics/i18n/translation/#the-set-language-redirect-view)), or the [Accept-Language](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) header to determine the used translation. I figured this would be the easiest and least intrusive way to figure out the translations, since adding a filter would require a lot of extra code.

I also fixed the issue with not being able to add custom resolvers for these fields, and you should now be able to override the behavior of these fields. You can also use them manually if you so which, they can be found from `graphene_django_extensions.translations` -> `TranslationsField` & `LanguageListField`. Let me know what you think!

**Comment by serdtsekol1** [comment]
I just checked, everything works perfectly, even better than I wanted )). The only thing, could you please tell me how to add the same translations but for InputObjectType?

```class ProductInput(graphene.InputObjectType):
    ...
    name ?
    
class Meta:
    model = Product```

**Comment by MrThearMan** [comment]
Released the experimental support (still behind the experimental flags) in [0.4.5](https://github.com/MrThearMan/graphene-django-extensions/releases/tag/v0.4.5). I'll likely make this the default in a future release.

As for mutations, this library encourages using either django forms or DRF serializers (prefered) for mutation without using graphene `InputObjectTypes`. I also hae some unsolved issues regarding language field validation for non-null translations and database constraints of base fields.

You can open another issue if you want to discuss improvements to the serializer or form approarches, but I'll likely be working on something in the near future. Closing this issue for now.
